#!/usr/bin/env bash
# ============================================================================
# bootstrap.sh — Zero-friction MCP setup for any Mac
#
# Usage: ./bootstrap.sh              (prompts for each credential)
#        ./bootstrap.sh --refresh    (re-resolve binary paths only, keep creds)
#        ./bootstrap.sh --verify     (check the generated config is valid)
#
# Creates ~/.mcp.json from .mcp.template.json with:
#   - Dynamic binary paths (npx, node, uvx) resolved at runtime
#   - Credentials read from ~/.env.mcp (created here, chmod 600, never committed)
#
# Leave a credential blank if you don't use that MCP server — you can delete the
# unused server block from ~/.mcp.json afterwards. Nothing is sent anywhere; all
# values stay on this machine.
# ============================================================================
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
TEMPLATE="${SCRIPT_DIR}/.mcp.template.json"
ENV_FILE="${HOME}/.env.mcp"
OUTPUT="${HOME}/.mcp.json"

RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'; CYAN='\033[0;36m'; NC='\033[0m'
info()  { echo -e "${CYAN}[INFO]${NC} $1"; }
ok()    { echo -e "${GREEN}[OK]${NC} $1"; }
warn()  { echo -e "${YELLOW}[WARN]${NC} $1"; }
fail()  { echo -e "${RED}[FAIL]${NC} $1"; exit 1; }

# ── Resolve binary paths ──────────────────────────────────────────────────
resolve_paths() {
  info "Resolving binary paths..."
  NPX_PATH=$(which npx 2>/dev/null || true)
  NODE_PATH=$(which node 2>/dev/null || true)
  UVX_PATH=$(which uvx 2>/dev/null || true)
  NPM_GLOBAL_ROOT=$(npm root -g 2>/dev/null || true)

  [[ -z "$NPX_PATH" ]]  && fail "npx not found. Install Node.js (via nvm) first."
  [[ -z "$NODE_PATH" ]] && fail "node not found. Install Node.js (via nvm) first."
  [[ -z "$UVX_PATH" ]]  && warn "uvx not found — the Redis MCP server won't work without it (pip install uv)."

  ok "npx:  $NPX_PATH"
  ok "node: $NODE_PATH"
  [[ -n "$UVX_PATH" ]] && ok "uvx:  $UVX_PATH" || true
  ok "npm global: $NPM_GLOBAL_ROOT"
  echo ""
}

# ── Prompt for a credential (blank allowed → skip that server) ─────────────
prompt_credential() {
  local var_name="$1" description="$2" current_value="${3:-}"
  if [[ -n "$current_value" ]]; then
    echo -e "  ${GREEN}${var_name}${NC}: [already set — Enter to keep, or paste new]"
    read -r -s new_value; echo ""
    [[ -n "$new_value" ]] && eval "export ${var_name}='${new_value}'" || eval "export ${var_name}='${current_value}'"
  else
    echo -e "  ${YELLOW}${var_name}${NC}: ${description} ${CYAN}(Enter to skip)${NC}"
    read -r -s value; echo ""
    eval "export ${var_name}='${value}'"
  fi
}

load_existing_credentials() {
  if [[ -f "$ENV_FILE" ]]; then
    info "Loading existing credentials from ${ENV_FILE}..."
    # shellcheck disable=SC1090
    source "$ENV_FILE"; ok "Loaded existing credentials"; echo ""; return 0
  fi
  return 1
}

collect_credentials() {
  info "Enter credentials (hidden as you type). Leave blank to skip a server."
  echo ""
  prompt_credential "SUPABASE_PROJECT_REF"  "Supabase project ref (the ID in your project URL)"          "${SUPABASE_PROJECT_REF:-}"
  prompt_credential "SUPABASE_ACCESS_TOKEN" "Supabase personal access token"                             "${SUPABASE_ACCESS_TOKEN:-}"
  prompt_credential "N8N_API_URL"           "n8n base URL (e.g. https://your-instance.app.n8n.cloud/)"   "${N8N_API_URL:-}"
  prompt_credential "N8N_API_KEY"           "n8n API key"                                                "${N8N_API_KEY:-}"
  prompt_credential "GITHUB_PAT"            "GitHub personal access token (repo + workflow scope)"       "${GITHUB_PAT:-}"
  prompt_credential "REDIS_HOST"            "Redis host (blank if unused)"                               "${REDIS_HOST:-}"
  prompt_credential "REDIS_PORT"            "Redis port (default 6379)"                                  "${REDIS_PORT:-6379}"
  prompt_credential "REDIS_PASSWORD"        "Redis password (blank if unused)"                           "${REDIS_PASSWORD:-}"
  prompt_credential "AIRTABLE_API_KEY"      "Airtable personal access token (blank if unused)"           "${AIRTABLE_API_KEY:-}"
  echo ""
}

save_credentials() {
  info "Saving credentials to ${ENV_FILE}..."
  cat > "$ENV_FILE" << ENVEOF
# MCP Credentials — generated by bootstrap.sh on $(date +%Y-%m-%d)
# NEVER commit this file. It is gitignored.
SUPABASE_PROJECT_REF='${SUPABASE_PROJECT_REF:-}'
SUPABASE_ACCESS_TOKEN='${SUPABASE_ACCESS_TOKEN:-}'
N8N_API_URL='${N8N_API_URL:-}'
N8N_API_KEY='${N8N_API_KEY:-}'
GITHUB_PAT='${GITHUB_PAT:-}'
REDIS_HOST='${REDIS_HOST:-}'
REDIS_PORT='${REDIS_PORT:-6379}'
REDIS_PASSWORD='${REDIS_PASSWORD:-}'
AIRTABLE_API_KEY='${AIRTABLE_API_KEY:-}'
ENVEOF
  chmod 600 "$ENV_FILE"
  ok "Credentials saved (chmod 600 — owner-only)"
}

generate_mcp_json() {
  info "Generating ${OUTPUT} from template..."
  [[ -f "$TEMPLATE" ]] || fail "Template not found: ${TEMPLATE}. Run from the repo root."
  export NPX_PATH NODE_PATH UVX_PATH NPM_GLOBAL_ROOT HOME
  export SUPABASE_PROJECT_REF SUPABASE_ACCESS_TOKEN N8N_API_URL N8N_API_KEY GITHUB_PAT
  export REDIS_HOST REDIS_PORT REDIS_PASSWORD AIRTABLE_API_KEY
  local VARS='${NPX_PATH} ${NODE_PATH} ${UVX_PATH} ${NPM_GLOBAL_ROOT} ${HOME}'
  VARS+=' ${SUPABASE_PROJECT_REF} ${SUPABASE_ACCESS_TOKEN} ${N8N_API_URL} ${N8N_API_KEY} ${GITHUB_PAT}'
  VARS+=' ${REDIS_HOST} ${REDIS_PORT} ${REDIS_PASSWORD} ${AIRTABLE_API_KEY}'
  envsubst "$VARS" < "$TEMPLATE" > "$OUTPUT"
  chmod 600 "$OUTPUT"
  ok "Generated ${OUTPUT} (chmod 600)"
}

verify_output() {
  info "Verifying generated config..."
  if ! python3 -c "import json; json.load(open('${OUTPUT}'))" 2>/dev/null; then
    fail "Generated ${OUTPUT} is not valid JSON!"
  fi
  ok "Valid JSON"
  local server_count
  server_count=$(python3 -c "import json; print(len(json.load(open('${OUTPUT}')).get('mcpServers', {})))")
  ok "${server_count} MCP servers configured (delete any you don't use from ${OUTPUT})"
  echo ""
}

main() {
  echo ""; echo "========================================"; echo "  MCP Bootstrap"; echo "========================================"; echo ""
  [[ -f "$TEMPLATE" ]] || fail "Template not found: ${TEMPLATE}. Run this from the repo root."
  resolve_paths

  if [[ "${1:-}" == "--verify" ]]; then
    [[ -f "$OUTPUT" ]] && { verify_output; ok "Verification complete!"; } || fail "No ${OUTPUT} found. Run bootstrap.sh first."
    exit 0
  fi

  if [[ "${1:-}" == "--refresh" ]]; then
    load_existing_credentials || fail "No existing credentials at ${ENV_FILE}. Run bootstrap.sh without --refresh first."
    info "Refreshing paths only (keeping existing credentials)..."
  else
    load_existing_credentials || true
    collect_credentials
    save_credentials
  fi

  generate_mcp_json
  verify_output

  echo -e "${GREEN}========================================"
  echo "  Setup complete!"
  echo "========================================"
  echo ""
  echo "  Config:      ${OUTPUT}"
  echo "  Credentials: ${ENV_FILE}"
  echo ""
  echo "  Next: Restart Claude Code / Cursor"
  echo "  Verify: ./bootstrap.sh --verify"
  echo "========================================${NC}"; echo ""
}

main "$@"
